# 请求文件日志
CREATE TABLE FILE_REQ_NOTIFY_LOG (
	ID	INTEGER	PRIMARY KEY,
	REQ_ID	VARCHAR2(20)	NOT NULL,
	RSP_ID	VARCHAR2(20),
	TENANT  VARCHAR2(32) NOT NULL,
	BIZ_TYPE	VARCHAR2(64)	NOT NULL,
	FILE_SERVICE	VARCHAR2(8)	NOT NULL,
	STATUS	VARCHAR2(16)	NOT NULL,
	STATE	VARCHAR2(32)	NOT NULL,
	ERROR_CODE	VARCHAR2(32),
	ERROR_MSG		VARCHAR2(512),
	FILE_PATH	VARCHAR2(1024)	NOT NULL,
	FILE_NAME	VARCHAR2(128)	NOT NULL,
	FILE_TIME	TIMESTAMP NOT NULL,
	LOCAL_FILE_PATH	VARCHAR2(1024),
	LOCAL_FILE_NAME	VARCHAR2(128),
	LOCAL_FILE_TIME	TIMESTAMP,
	CONFIRM_DATA	VARCHAR2(216),
	DUBBO_GROUP	VARCHAR2(32),
	DUBBO_VERSION	VARCHAR2(16),
	PARTNER_ID	VARCHAR2(20) NOT NULL,
	GID	VARCHAR2(35) NOT NULL,
	MERCHANT_ORDER_NO	VARCHAR2(64),
	RAW_ADD_TIME  TIMESTAMP NOT NULL,
  RAW_UPDATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE UNIQUE INDEX UIDX_REQ_REQID ON FILE_REQ_NOTIFY_LOG(REQ_ID,TENANT);
COMMENT ON TABLE FILE_REQ_NOTIFY_LOG IS '请求文件日志';
COMMENT ON COLUMN FILE_REQ_NOTIFY_LOG.REQ_ID IS '请求号,批次号';
COMMENT ON COLUMN FILE_REQ_NOTIFY_LOG.RSP_ID IS '响应id';
COMMENT ON COLUMN FILE_REQ_NOTIFY_LOG.TENANT IS '租户';
COMMENT ON COLUMN FILE_REQ_NOTIFY_LOG.BIZ_TYPE IS '业务类型';
COMMENT ON COLUMN FILE_REQ_NOTIFY_LOG.FILE_SERVICE IS '文件服务';
COMMENT ON COLUMN FILE_REQ_NOTIFY_LOG.STATUS IS '业务状态';
COMMENT ON COLUMN FILE_REQ_NOTIFY_LOG.STATE IS '系统状态';
COMMENT ON COLUMN FILE_REQ_NOTIFY_LOG.ERROR_CODE IS '错误码';
COMMENT ON COLUMN FILE_REQ_NOTIFY_LOG.ERROR_MSG IS '错误信息';
COMMENT ON COLUMN FILE_REQ_NOTIFY_LOG.FILE_PATH IS '本地文件路径';
COMMENT ON COLUMN FILE_REQ_NOTIFY_LOG.LOCAL_FILE_PATH IS '文件路径';
COMMENT ON COLUMN FILE_REQ_NOTIFY_LOG.FILE_NAME IS '文件名';
COMMENT ON COLUMN FILE_REQ_NOTIFY_LOG.LOCAL_FILE_NAME IS '本地文件名';
COMMENT ON COLUMN FILE_REQ_NOTIFY_LOG.FILE_TIME IS '文件时间戳';
COMMENT ON COLUMN FILE_REQ_NOTIFY_LOG.LOCAL_FILE_TIME IS '本地文件时间戳';
COMMENT ON COLUMN FILE_REQ_NOTIFY_LOG.CONFIRM_DATA IS '确认数据';
COMMENT ON COLUMN FILE_REQ_NOTIFY_LOG.DUBBO_GROUP IS 'dubbo分组';
COMMENT ON COLUMN FILE_REQ_NOTIFY_LOG.DUBBO_VERSION IS 'dubbo版本';
COMMENT ON COLUMN FILE_REQ_NOTIFY_LOG.PARTNER_ID IS '合作商户id';
COMMENT ON COLUMN FILE_REQ_NOTIFY_LOG.GID IS 'gid';
COMMENT ON COLUMN FILE_REQ_NOTIFY_LOG.MERCHANT_ORDER_NO IS '商户订单号';



# 响应文件日志
CREATE TABLE FILE_RSP_NOTIFY_LOG (
	ID	INTEGER	PRIMARY KEY,
	RSP_ID	VARCHAR2(20) NOT NULL,
	REQ_ID	VARCHAR2(20),
	TENANT  VARCHAR2(32) NOT NULL,
	BIZ_TYPE	VARCHAR2(64)	NOT NULL,
	FILE_SERVICE	VARCHAR2(8)	NOT NULL,
	STATUS	VARCHAR2(16)	NOT NULL,
	STATE	VARCHAR2(32)	NOT NULL,
	ERROR_CODE	VARCHAR2(32),
	ERROR_MSG		VARCHAR2(512),
	FILE_PATH	VARCHAR2(1024),
	FILE_NAME	VARCHAR2(128),
	FILE_TIME	TIMESTAMP,
	LOCAL_FILE_PATH	VARCHAR2(1024)	NOT NULL,
	LOCAL_FILE_NAME	VARCHAR2(128)	NOT NULL,
	LOCAL_FILE_TIME	TIMESTAMP	NOT NULL,
	CONFIRM_DATA	VARCHAR2(216),
	DUBBO_GROUP	VARCHAR2(32),
	DUBBO_VERSION	VARCHAR2(16),
	PARTNER_ID	VARCHAR2(20) NOT NULL,
	GID	VARCHAR2(35) NOT NULL,
	MERCHANT_ORDER_NO	VARCHAR2(64),
	RAW_ADD_TIME  TIMESTAMP NOT NULL,
  RAW_UPDATE_TIME TIMESTAMP DEFAULT SYSTIMESTAMP
);
CREATE UNIQUE INDEX UIDX_RSP_NOTIFY ON FILE_RSP_NOTIFY_LOG(RSP_ID,TENANT);
COMMENT ON TABLE FILE_RSP_NOTIFY_LOG IS '响应文件日志';
COMMENT ON COLUMN FILE_RSP_NOTIFY_LOG.RSP_ID IS '响应id,批次号';
COMMENT ON COLUMN FILE_RSP_NOTIFY_LOG.REQ_ID IS '请求号';
COMMENT ON COLUMN FILE_RSP_NOTIFY_LOG.TENANT IS '租户';
COMMENT ON COLUMN FILE_RSP_NOTIFY_LOG.BIZ_TYPE IS '业务类型';
COMMENT ON COLUMN FILE_REQ_NOTIFY_LOG.FILE_SERVICE IS '文件服务';
COMMENT ON COLUMN FILE_RSP_NOTIFY_LOG.STATUS IS '业务状态';
COMMENT ON COLUMN FILE_RSP_NOTIFY_LOG.STATE IS '系统状态';
COMMENT ON COLUMN FILE_RSP_NOTIFY_LOG.ERROR_CODE IS '错误码';
COMMENT ON COLUMN FILE_RSP_NOTIFY_LOG.ERROR_MSG IS '错误信息';
COMMENT ON COLUMN FILE_RSP_NOTIFY_LOG.FILE_PATH IS '文件路径';
COMMENT ON COLUMN FILE_RSP_NOTIFY_LOG.LOCAL_FILE_PATH IS '本地文件路径';
COMMENT ON COLUMN FILE_RSP_NOTIFY_LOG.FILE_NAME IS '文件名';
COMMENT ON COLUMN FILE_RSP_NOTIFY_LOG.LOCAL_FILE_NAME IS '本地文件名';
COMMENT ON COLUMN FILE_RSP_NOTIFY_LOG.FILE_TIME IS '文件时间戳';
COMMENT ON COLUMN FILE_RSP_NOTIFY_LOG.LOCAL_FILE_TIME IS '本地文件时间戳';
COMMENT ON COLUMN FILE_RSP_NOTIFY_LOG.CONFIRM_DATA IS '确认数据';
COMMENT ON COLUMN FILE_RSP_NOTIFY_LOG.DUBBO_GROUP IS 'dubbo分组';
COMMENT ON COLUMN FILE_RSP_NOTIFY_LOG.DUBBO_VERSION IS 'dubbo版本';
COMMENT ON COLUMN FILE_RSP_NOTIFY_LOG.PARTNER_ID IS '合作商户id';
COMMENT ON COLUMN FILE_RSP_NOTIFY_LOG.GID IS 'gid';
COMMENT ON COLUMN FILE_RSP_NOTIFY_LOG.MERCHANT_ORDER_NO IS '商户订单号';

create sequence SEQ_FILEFRONT
minvalue  1
maxvalue  99999999999999999999
start  with  1
increment  by  1
cache  20;